version: 2.1


jobs:
    create_infra:
        docker:
            - image: python:3.7-alpine3.11
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - 'cb:0f:b9:db:cc:de:24:f9:05:a9:48:de:73:0e:f2:9e'
            - run:
                name: Install Ansible
                command: |
                    apk add --update ansible
            - run:
                name: Run Playbook and configure server
                command: |
                    ansible-playbook -i inventory main.yml


workflows:
    default:
        jobs:
            - create_infra
